function make_ghost () {
    ghost = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    ghost,
    [img`
        ........................
        ........................
        ........................
        ........................
        ........22222222........
        .......22aaaaaa22.......
        .......2aaaaaaaa2.......
        ......2222aaaa2222......
        ......2af22aa22fa2......
        .....22af1aaaa1fa2......
        .....2aaaaaaaaaaa2......
        .....2aaaaaaaaaaa22.....
        .....2aaffaaaaffaa2.....
        .....2aaaffffffaaa2.....
        ....22aaa1aaaa1aaa22....
        ....2aaa1aaaaaa1aaa2....
        ....2aaa1aaaaaa1aaa2....
        ....2aaaaaaaaaaaaaa2....
        ...2aaaaaaaaaaa2222a2...
        ...2222aa2222a22..222...
        ...22.2aa2..2a2...22....
        ......22a2..2a2.........
        .......2a2..222.........
        .......222..............
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........22222222........
        .......22aaaaaa22.......
        .......22aaaaaa22.......
        ......22a2aaaa2a22......
        ......2af22aa22fa2......
        .....22af1aaaa1fa2......
        .....2aaaaaaaaaaa2......
        .....2aaaaaaaaaaa22.....
        .....2aaaffffffaaa2.....
        .....2aaa1aaaa1aaa2.....
        ....22aaa1aaaa1aaa22....
        ....2aaa1aaaaaa1aaa2....
        ....2aaaaaaaaaaaaaa2....
        ....2aaaaaaaaaaaaaa2....
        ....2aaaaaaaaaa222a2....
        ....2222a2222a22.222....
        ....22.2a2..2a2..22.....
        .......222..222.........
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........22222222........
        .......22aaaaaa22.......
        .......2aaaaaaaa2.......
        ......22a2aaaa2a22......
        ......2aaf2aa2faa2......
        .....22aaf1221faa2......
        .....2aaaaaaaaaaa2......
        .....2aaaaaaaaaaa22.....
        .....2aaafffffffaa2.....
        .....2aaaa1aaa1aaa2.....
        ....22aaaa1aaa1aaa22....
        ....2aaaaaaaaaaaaaa2....
        ....2aaaaaaaaaaaaaa2....
        ...2aaaaaaaaaaaaaaa2....
        ...2a222aaa2222a22aa2...
        ...22..22a22..2a2.22....
        ........2a2...2a2.......
        ........2a2...222.......
        ........222.............
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ........22222222........
        .......22aaaaaa22.......
        .......2aaaaaaaa2.......
        ......222aaaaaa222......
        ......2af2aaaa2fa2......
        .....22af12aa21fa2......
        .....2aaaaaaaaaaa2......
        .....2aaaaaaaaaaa22.....
        .....2aaafffffffaa2.....
        .....2aaaa1aaa1aaa2.....
        ....22aaaa1aaa1aaa22....
        ....2aaaaaaaaaaaaaa2....
        ....2aaaaaaaaaaaaaa2....
        ....2aaaaaaaaaaaaaa2....
        ...2aaaaaaaaaaa222a2....
        ...2222aaa22aaa2.2a2....
        ...22..2a2..2a2..222....
        .......2a2..2a2..22.....
        .......222..2a2.........
        ............222.........
        `],
    200,
    true
    )
    tiles.placeOnRandomTile(ghost, assets.tile`myTile2`)
    ghost.follow(MAREO, 80)
}
function make_stare () {
    stare = sprites.create(img`
        . . . . . . . . . . . . . 8 . . 
        . . 9 . . 9 . 2 b . . 2 . . . . 
        . 9 9 9 . . . b 5 b . . . . . . 
        . . 9 . 9 . b 5 5 5 b . . 2 . . 
        3 . . . . b b 5 5 5 b b . . . . 
        . . b b b b 5 5 5 5 5 b b b b . 
        . . b 5 5 5 f 5 5 f 5 5 5 5 b . 
        . . b 5 5 5 f 5 2 f 5 5 5 5 b . 
        . . . b 3 8 5 5 5 7 5 5 5 b . . 
        3 . 7 7 3 3 7 5 2 7 7 5 b . . 8 
        . . . 7 8 7 5 7 7 7 5 5 b . . . 
        . . . 8 8 9 9 5 5 5 5 5 5 c . . 
        . . 3 c 9 8 5 c c c 5 5 5 c . . 
        . 3 3 3 9 c 8 . . . c c c c . 7 
        . . 3 . . . . . 8 . . . 7 . . . 
        . . . . . . . . 8 . . . . 7 . . 
        `, SpriteKind.Food)
}
function make_mareo () {
    MAREO = sprites.create(img`
        . . . . . 2 2 . 2 2 . . . . . . 
        . . . . . 2 . 2 . 2 . . . . . . 
        . . . . . 2 . . . 2 . . . . . . 
        . . . . . 2 . f f f f . . . . . 
        . . . . . f f 2 1 2 1 f f . . . 
        . . . . f 2 2 1 2 1 2 1 2 f . . 
        . . . . f f f f f f f f f f . . 
        . . . f 4 f 2 2 2 2 2 2 f 4 f . 
        . . . f 4 4 f f f f f f 4 4 f . 
        . . . f 4 4 1 f 4 4 f 1 4 4 f . 
        . . . f 4 4 4 e d d e 4 4 4 f . 
        . . . f 4 4 4 4 e e 4 4 4 4 f . 
        . . . . f 4 4 4 1 1 4 4 4 f . . 
        . . . . . f f f f f f f f . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Player)
    controller.moveSprite(MAREO)
    tiles.placeOnRandomTile(MAREO, assets.tile`myTile1`)
    tiles.setTileAt(MAREO.tilemapLocation(), assets.tile`transparency16`)
    scene.cameraFollowSprite(MAREO)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    game.gameOver(true)
})
function make_ghost2 () {
    ghost = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    ghost,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ..7.....ff1111ff........
        .777...fb11aa11bf.......
        ..7....f11aaaa11f.......
        ..f...fd11aaaa11df......
        ..ff..fd11a1a111df......
        ...ff.fddd1111dddf......
        ...ff.fbdbfddfbdbf......
        ....fffcdcf11fcdcf......
        .....fffb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ...bf1f1ffbffb1f1f1fb...
        ...bbbbbbbbffbbbbbbbb...
        ...22222222ff22222222...
        ........22....22........
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        .....7..................
        ....777...ffff..........
        .....7..ff1111ff........
        ....ff.fb11aa11bf.......
        ...ff..f11aaaa11f.......
        ...ff.fd11aaaa11df......
        ...ff.fd111a1a11df......
        ...ff.fddd1111dddf......
        ...ffffbdbfddfbdbf......
        ....fffcdcf11fcdcf......
        .....fffb111111ffff.....
        ......fffcdb1bc111cf....
        ....fc111cbfbf1b1b1f....
        ....f1b1b1fffb1f1f1fb...
        ...bf1f1ffbffbbbbbbbb...
        ...bbbbbbbbff22222222...
        ...22222222ff...2.......
        .....222................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ...7....................
        ..777...................
        ...7....................
        ...f......ffff..........
        ...f....ff1111ff........
        ..ff...fb11aa11bf.......
        ..ff...f11aaaa11f.......
        ..ff..fd11aaaa11df......
        ...ff.fd11a1a111df......
        ...ff.fddd1111dddf......
        ....fffbdbfddfbdbf......
        ....fffcdcf11fcdcf......
        .....fffb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ...bf1f1ffbffb1f1f1fb...
        ...bbbbbbbbffbbbbbbbb...
        ...22222222ff22222222...
        ....22...........22.....
        .....2...........2......
        ........................
        ........................
        `,img`
        ........................
        ...fff..................
        ..ffffff................
        ..ff...7................
        ..ff..777.ffff..........
        ..ff...7ff1111ff........
        ..ff...fb11aa11bf.......
        ..ff...f11aaaa11f.......
        ..fff.fd11aaaa11df......
        ..fff.fd111a1a11df......
        ...ffffddd1111dddf......
        ...ffffbdbfddfbdbf......
        ....fffcdcf11fcdcf......
        .....ffff111111bf.......
        ....fc111cdb1bdfff......
        ....f1b1bcbfbfc111cf....
        ...bf1f1fbffff1b1b1f....
        ...bbbbbbbfffbff1f1fb...
        ...2222222fffbbbbbbbb...
        .....22....ff22222222...
        .....22.........222.....
        ................222.....
        ................2.......
        ........................
        `],
    100,
    true
    )
    tiles.placeOnRandomTile(ghost, assets.tile`myTile0`)
    ghost.follow(MAREO, 85)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let stare: Sprite = null
let MAREO: Sprite = null
let ghost: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
make_mareo()
make_stare()
make_ghost()
make_ghost2()
game.onUpdateInterval(1000, function () {
    stare.setVelocity(randint(-200, 200), randint(-200, 200))
})
